/**
 * Created by zhu on 2016/10/20.
 *
 */
const routers=[
    {
        path:'/',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index.vue'))//打包切割
            });
        }
    },
    {
        path:'/index1',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index1.vue'))
            });
        }
    },
    {
        path:'/index2',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index2.vue'))
            });
        }
    },
    {
        path:'/index3',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index3.vue'))
            });
        }
    },
    {
        path:'/index4',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index4.vue'))
            });
        }
    },
    {
        path:'/index5',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index5.vue'))
            });
        }
    },
    {
        path:'/address',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/address.vue'))
            });
        }
    },
    {
        path:'/index6',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/index6.vue'))
            });
        }
    },
    {
        path:'/class',component(resolve){
            require.ensure(['./components/index.vue'],()=>{
                resolve(require('./components/class.vue'))
            });
        }
    }
];
export default routers;
